# Generated by Django 4.1.7 on 2024-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_wishlist_review_productfaq_notification_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
